org: jhaemel
app: xibix-challenge
service: xibix-challenge

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  calculateViewSpots:
    handler: handler.calculateViewSpots
